artifact_uri: file:///Users/trishashishodiya/Documents/My projects/Churn Prediction/churn-platform/mlflow_runs/619397080990749070/4c013209e1174af3bcb456a58f23df63/artifacts
end_time: 1782240536498
entry_point_name: ''
experiment_id: '619397080990749070'
lifecycle_stage: active
run_id: 4c013209e1174af3bcb456a58f23df63
run_name: xgboost_tuned
source_name: ''
source_type: 4
source_version: ''
start_time: 1782240518239
status: 3
tags: []
user_id: trishashishodiya
