artifact_location: file:///Users/trishashishodiya/Documents/My projects/Churn Prediction/churn-platform/mlflow_runs/0
creation_time: 1782240513849
experiment_id: '0'
last_update_time: 1782240513849
lifecycle_stage: active
name: Default
