artifact_location: file:///Users/trishashishodiya/Documents/My projects/Churn Prediction/churn-platform/mlflow_runs/619397080990749070
creation_time: 1782240513857
experiment_id: '619397080990749070'
last_update_time: 1782240513857
lifecycle_stage: active
name: churn-prediction
